name: Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install and Setup Dependencies
      run: |
        git checkout faccfa4823b26bdc0e8c7a1e88f5a389997961c1
        sudo apt-get update -y && sudo apt-get install -y build-essential clang bison flex libreadline-dev
        sudo apt-get install -y gawk tcl-dev libffi-dev git mercurial graphviz
        sudo apt-get install -y xdot pkg-config python python3 libftdi-dev
        sudo apt-get install -y qt5-default python3-dev libboost-all-dev cmake libeigen3-dev
        sudo apt-get install -y yosys
        sudo apt-get install binutils gcc-avr avr-libc
        git clone https://github.com/YosysHQ/icestorm.git icestorm
        git clone https://github.com/cseed/arachne-pnr.git arachne-pnr
        git clone https://github.com/YosysHQ/nextpnr nextpnr
        cd icestorm
        make
        sudo make install
        cd ..
        cd arachne-pnr
        make
        sudo make install
        cd ..
        cd nextpnr
        cmake -DARCH=ice40 -DCMAKE_INSTALL_PREFIX=/usr/local .
        make
        sudo make install
        cd ..
    - name: Compile
      run: |
        make -j
